name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run: |
          npm ci
          npm run build
      - name: Get example (well formed) applications
        run: |
          wget "https://raw.githubusercontent.com/w3f/Grant-Milestone-Delivery/master/deliveries/admeta_milestone_1.md"
          wget "https://raw.githubusercontent.com/w3f/Grant-Milestone-Delivery/master/maintenance_deliveries/Substratesnap_Maintenance-2.md"
      - name: Test action (normal application)
        uses: ./
        with:
          path: admeta_milestone_1.md
      - name: Test action (maintenance application)
        uses: ./
        with:
          path: Substratesnap_Maintenance-2.md


          